#!{{pkgPathFor "core/bash"}}/bin/bash -xe
#
exec 2>&1

source "{{pkg.svc_config_path}}/config.sh"

cd {{pkg.svc_path}}

concourse worker \
 --work-dir {{cfg.work_dir}} \
 {{~#if bind.web ~}}
 {{#with bind.web.first as |web| }}
 --tsa-host {{web.sys.ip}} \
 {{/with ~}}
 {{else ~}}
 --tsa-host 127.0.0.1 \
 {{/if ~}}
 --tsa-public-key {{pkg.svc_files_path}}/tsa_host_key.pub \
 --tsa-worker-private-key {{pkg.svc_files_path}}/worker_key
