#!/bin/bash -xe
#
exec 2>&1

source "{{pkg.svc_config_path}}/config.sh"

cd {{pkg.svc_path}}

PG_PASS=$CONCOURSE_POSTGRES_PASSWORD
PG_HOST=$CONCOURSE_POSTGRES_HOST

if PGPASSWORD=$PG_PASS psql -lqt -h $PG_HOST -U $CONCOURSE_POSTGRES_USER | cut -d \| -f 1 | grep -qw concourse; then
    echo "first thing it work fine"
else
    PGPASSWORD=$PG_PASS createdb $CONCOURSE_POSTGRES_DATABASE -h $PG_HOST -U $CONCOURSE_POSTGRES_USER
fi

concourse web \
    --session-signing-key {{pkg.svc_files_path}}/session_signing_key \
    --tsa-host-key {{pkg.svc_files_path}}/tsa_host_key \
    --tsa-authorized-keys {{pkg.svc_files_path}}/authorized_worker_keys 