---
meta:
  delmo:
    machine_name: habitat-plans-pipeline-machine

  github:
    ci_auth_token: REDACTED

  dockerhub:
    email: REDACTED
    username: REDACTED
    password: REDACTED

  habitat:
    origin_key: REDACTED
    auth_token: REDACTED
    origin: core

  aws:
    docker-machine-bucket: docker-machine-bucket
    access_key_id: REDACTED
    secret_access_key: REDACTED
    region: us-east-1


groups:
- name: images
  jobs: [build-hab-ci, build-hab-delmo, build-docker-machine-setup, build-habitat-plans-pipeline-image]

jobs:
- name: build-hab-ci
  plan:
    - {get: hab-ci-setup, trigger: true}
    - put: hab-ci-image
      params:
        build: hab-ci-setup/images/hab-ci

- name: build-hab-delmo
  plan:
    - {get: hab-delmo-setup, trigger: true}
    - put: hab-delmo-image
      params:
        build: hab-delmo-setup/images/hab-delmo

- name: build-docker-machine-setup
  plan:
    - {get: docker-machine-setup, trigger: true}
    - put: docker-machine-setup-image
      params:
        build: docker-machine-setup/images/docker-machine-setup

- name: build-habitat-plans-pipeline-image
  public: true
  plan:
  - aggregate:
    - {get: habitat-plans-pipeline, trigger: true}
    - {get: habitat-release, trigger: true}
  - put: habitat-plans-pipeline-image
    params:
      build: habitat-plans-pipeline/images/habitat-plans-pipeline
      tag: habitat-release/version
      tag_as_latest: true

resources:

- name: hab-ci-setup
  type: git
  source:
    uri: https://github.com/eeyun/hab-ci
    paths: [images/hab-ci/*]

- name: docker-machine-setup
  type: git
  source:
    uri: https://github.com/eeyun/hab-ci
    paths: [images/docker-machine-setup/*]

- name: hab-delmo-setup
  type: git
  source:
    uri: https://github.com/eeyun/hab-ci
    paths: [images/hab-delmo/*]

- name: hab-ci-image
  type: docker-image
  source:
    email: (( grab meta.dockerhub.email ))
    username: (( grab meta.dockerhub.username ))
    password: (( grab meta.dockerhub.password ))
    repository: eeyun/hab-ci

- name: docker-machine-setup-image
  type: docker-image
  source:
    email: (( grab meta.dockerhub.email ))
    username: (( grab meta.dockerhub.username ))
    password: (( grab meta.dockerhub.password ))
    repository: eeyun/docker-machine-setup

- name: hab-delmo-image
  type: docker-image
  source:
    email: (( grab meta.dockerhub.email ))
    username: (( grab meta.dockerhub.username ))
    password: (( grab meta.dockerhub.password ))
    repository: eeyun/hab-delmo

- name: habitat-release
  type: github-release
  source:
    user:         habitat-sh
    repository:   habitat
    access_token: (( grab meta.github.ci_auth_token ))

- name: habitat-plans-pipeline
  type: git
  source:
    uri: https://github.com/habitat-sh/plan-ci.git
    paths: [images/habitat-plans-pipeline/*]

- name: habitat-plans-pipeline-image
  type: docker-image
  source:
    email: (( grab meta.dockerhub.email ))
    username: (( grab meta.dockerhub.username ))
    password: (( grab meta.dockerhub.password ))
    repository: eeyun/habitat-plans-pipeline
