#!/bin/bash

PIPELINE=$(cd $(dirname ${BASH_SOURCE[0]}) ; pwd)

pushd $PIPELINE >/dev/null
  trap "rm -f ${PIPELINE}/.deploy.yml" INT QUIT TERM EXIT
  spruce merge base.yml > .deploy.yml && \
    REDACT=yes spruce merge --prune meta base.yml > pipeline.yml && \
    fly --target lite2 set-pipeline --pipeline habitat-ci --config .deploy.yml     &&
    fly --target lite2 unpause-pipeline --pipeline habitat-ci

  rm -rf packages tests
popd >/dev/null
